RRECOMMENDS_${PN} += 'kernel-module-iscsi-target-mod'
RRECOMMENDS_${PN} += 'kernel-module-target-core-file'
RRECOMMENDS_${PN} += 'kernel-module-target-core-iblock'
RRECOMMENDS_${PN} += 'kernel-module-target-core-mod'
RRECOMMENDS_${PN} += 'kernel-module-target-core-pscsi'
